<?php
/**
 * Cgi Book Module
 *
 * @category   Cgi
 * @package    Cgi_Book
 * @version    1.0.0
 * @description view file
 *
 * Release with version 1.0.0
 *
 *
 */
?>
<div class="my-books">
    <div class="row datatable-search-block">
        <div class="col-md-4 col-sm-6 col-xs-12 mt-xs-20 datatable-search-box">
            <input type="text" name="bookTitle" id="book-title" aria-controls="datatable-book" class="ecode-filter" placeholder="Search Book Name" />
            <button id="book-title-btn" class="searchIco" title="Search">Search</button>
            <button id="book-title-clear-btn" class="clearIco" title="Reset">Reset</button>
        </div>
    </div>

    <table id="datatable-book" class="table table-striped table-bordered greenhead rwd-table" style="width:100%">
        <thead>
            <tr>
                <th class=""><?php /* @escapeNotVerified */ echo __('Book Name') ?></th>
                <th class=""><?php /* @escapeNotVerified */ echo __('ISBN') ?></th>
            </tr>
        </thead>
    </table>

</div>
<script type="text/x-magento-init">
    {
        "*" : {
            "book": {}
        }
    }
</script>